Add an npm start script to project template
o1-labs/zkapp-cli pull request #204
Opened 2022-06-02 22:17 UTC by ymekuria

**Description**
Fixes
#203 

Add npm start script to the project template for example projects and update example project comment instructions. Currently the user is shown these instructions after creating an example project. 

To run the example:
  cd sudoku
  npm run test
  npm run build
  npm run start

Now a user can type npm start to run an example.

**Tested**
Successfully used this version of the CLI to create new projects without a start script, and new example projects with a start script on the package.json.

2022-07-05 14:40 UTC, jasongitmail requested changes

2022-07-05 14:40 UTC, jasongitmail commented on src/lib/example.js
> +  let packageJsonContent = JSON.parse(fs.readFileSync(file, 'utf8'));
We're using [fs-extra](https://www.npmjs.com/package/fs-extra), so we can simplify the value to `fs.readJsonSync(file)` ([src](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/readJson-sync.md))

2022-07-05 14:40 UTC, jasongitmail commented on src/lib/example.js
> +  fs.writeFileSync(file, JSON.stringify(packageJsonContent, null, 2));
[`fs.writeJsonSync()`](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/writeJson-sync.md)

2022-07-05 14:40 UTC, jasongitmail commented on src/lib/example.js
> +  const startScript = 'node build/src/index.js';
Would probably simplify to not use a var. Should be `'node build/src/run.js'` now right?

2022-07-06 20:53 UTC, jasongitmail approved these changes
LGTM!

2022-07-06 20:53 UTC, jasongitmail commented on src/lib/example.js
> +  // Add start script to template package.json
small nit: seems redundant to have this given how small the method is

2022-07-06 22:38 UTC, merged

2022-07-06 22:42 UTC, ymekuria commented
A start script was added in [this](https://github.com/o1-labs/zkapp-cli/pull/204) PR.